name: Tests
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...
